config/routes.rb
Rails.application.routes.draw do
  resources :texts
  root 'text#text'
  post '' => 'text#create'
  get 'messages/:id' => 'text#read'
  
  post'notes/api' => 'text#c_json'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/text.rb
class Text < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/text_controller.rb
class TextController < ApplicationController
  require 'json'
  require 'net/http'

  $message = ""
  $id = 0
  def index
  end

  def create
    $message = params[:text]
    Text.create(:text => $message, :number => $id)
    $id = $id + 1
    render plain: "https://texthider.herokuapp.com/messages/" + $id.to_s
  end

  def read
      render plain: Text.find_by(:number => ($id - 1)).text
      Text.destroy_all
  end

  def c_json

    if request.headers["Content-Type"] == 'application/json'
      $message = params[:message]
      Text.create(:text => $message, :number => $id)
      $id = $id + 1
      url = "https://texthider.herokuapp.com/messages/" + $id.to_s
      render plain: "'"'{"url":' + '"' + url.to_s + '"}'"'" + "\n"
    end

    if request.headers["Content-Type"] == 'text/xml'
      $message = Nokogiri::XML(request.body.read).content
      Text.create(:text => $message, :number => $id)
      $id = $id + 1
      url = "https://texthider.herokuapp.com/messages/" + $id.to_s
      render plain: '<url>' + url.to_s + '</url>' + "\n"
    end

  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:text, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/text_helper.rb
module TextHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Texthider</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/text/text.html.erb
<%= form_tag({}, multipart: true) do %>
  <%= text_area_tag 'text' %>
  <%= submit_tag 'Upload text' %>
<% end %>

app/views/texts/_form.html.erb
<%= form_with(model: text, local: true) do |form| %>
  <% if text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :text_text %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :text_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Texts</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.text %></td>
        <td><%= text.number %></td>
        <td><%= link_to 'Show', text %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text', new_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @text.text %>
</p>

<p>
  <strong>Number:</strong>
  <%= @text.number %>
</p>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>